spring:
  profiles:
    include: oauth, aws
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

---
spring:
  profiles: local

logging:
  file:
    path: ./logs/local
    name: local_log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 60000
      connection-timeout: 3000
    url: jdbc:mysql://localhost:3306/zeze?serverTimezone=Asia/Seoul
    username: mariadb
    password: root
logging:
  config: classpath:logback-spring.xml
